# @package _global_

defaults:
  - _self_
  - data: lrs3.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: voiceformerae.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# initialise the model with external previous model weights
init_from: null

# passing checkpoint path is necessary for evaluation
ckpt_path: None

seed: 2038
